wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1706513866.353005
    t:
      1:
      - 1
      - 40
      - 41
      - 51
      - 55
      - 105
      2:
      - 1
      - 40
      - 41
      - 51
      - 53
      - 55
      - 105
      3:
      - 7
      - 23
      4: 3.10.12
      5: 0.16.2
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
pad_token:
  desc: null
  value: 0
metric_fx:
  desc: null
  value: decode_batch
token_size:
  desc: null
  value: 369
n_layers:
  desc: null
  value: 17
d_model:
  desc: null
  value: 768
heads:
  desc: null
  value: 12
conv_dims:
  desc: null
  value:
  - 512
  - 512
  - 512
  - 512
  - 512
  - 512
  - 512
kernel_sizes:
  desc: null
  value:
  - 10
  - 3
  - 3
  - 3
  - 3
  - 2
  - 2
strides:
  desc: null
  value:
  - 5
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
dropout_rate:
  desc: null
  value: 0.1
